import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vitepress";

const __dirname = fileURLToPath(new URL(".", import.meta.url));

// Sidebar is generated by TypeDoc into docs/api/; fall back to empty until first `typedoc` run.
let sidebar = [];
try {
  sidebar = JSON.parse(readFileSync(resolve(__dirname, "../typedoc-sidebar.json"), "utf-8"));
} catch {}

// VitePress dev server doesn't support sub-path base; use root in dev.
const base = process.env.NODE_ENV === "production" ? "/bireactive/api/" : "/";

export default defineConfig({
  title: "bireactive",
  description: "Bi-directional reactive programming",
  base,
  outDir: resolve(__dirname, "../../dist-web/api"),
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: "Demo", link: "https://orionreed.github.io/bireactive/" },
      { text: "GitHub", link: "https://github.com/OrionReed/bireactive" },
    ],
    sidebar,
    search: { provider: "local" },
    socialLinks: [{ icon: "github", link: "https://github.com/OrionReed/bireactive" }],
  },
});
