// custom elements available in *.md to render in the prose (e.g. bireactive.md)

import { MdMarker, MdTex } from "@bireactive/web";
import { DarkModeToggle } from "./dark-mode-toggle";
import { GithubLink } from "./github-link";
import { MdAllen } from "./md-allen";
import { MdAnchors } from "./md-anchors";
import { MdBboxHandles } from "./md-bbox-handles";
import { MdBehaviors } from "./md-behaviors";
import { MdBestFit } from "./md-best-fit";
import { MdBezierGestalt } from "./md-bezier-gestalt";
import { MdBireactive } from "./md-bireactive";
import { MdBireactiveEq } from "./md-bireactive-eq";
import { MdBoolBridges } from "./md-bool-bridges";
import { MdBudgetTree } from "./md-budget-tree";
import { MdCancel } from "./md-cancel";
import { MdCanvasField } from "./md-canvas-field";
import { MdCanvasGraph } from "./md-canvas-graph";
import { MdCentering } from "./md-centering";
import { MdChoreography } from "./md-choreography";
import { MdCircuit } from "./md-circuit";
import { MdClampQuantize } from "./md-clamp-quantize";
import { MdCloth } from "./md-cloth";
import { MdCode } from "./md-code";
import { MdConfocal } from "./md-confocal";
import { MdConformalDisc } from "./md-conformal-disc";
import { MdContainmentForest } from "./md-containment-forest";
import { MdCurveBases } from "./md-curve-bases";
import { MdDebugger } from "./md-debugger";
import { MdEquation } from "./md-equation";
import { MdFigure8 } from "./md-figure8";
import { MdFlags } from "./md-flags";
import { MdFourier } from "./md-fourier";
import { MdFractalTree } from "./md-fractal-tree";
import { MdGears } from "./md-gears";
import { MdGraph } from "./md-graph";
import { MdHandles } from "./md-handles";
import { MdHeatmap } from "./md-heatmap";
import { MdHistogram } from "./md-histogram";
import { MdIk } from "./md-ik";
import { MdIncidence } from "./md-incidence";
import { MdInvertible } from "./md-invertible";
import { MdKeplerSystem } from "./md-kepler-system";
import { MdLayoutDemo } from "./md-layout-demo";
import { MdLensAlgebra } from "./md-lens-algebra";
import { MdLerps } from "./md-lerps";
import { MdLoop } from "./md-loop";
import { MdMadlibs } from "./md-madlibs";
import { MdMerge } from "./md-merge";
import { MdMirror } from "./md-mirror";
import { MdMix } from "./md-mix";
import { MdMorph } from "./md-morph";
import { MdMultitouch } from "./md-multitouch";
import { MdMultitrack } from "./md-multitrack";
import { MdNetworkLens } from "./md-network-lens";
import { MdOscillator } from "./md-oscillator";
import { MdParticles } from "./md-particles";
import { MdPropFlex } from "./md-prop-flex";
import { MdPropGeom } from "./md-prop-geom";
import { MdPropSudoku } from "./md-prop-sudoku";
import { MdPropTypes } from "./md-prop-types";
import { MdPulley } from "./md-pulley";
import { MdRand } from "./md-rand";
import { MdRcc8 } from "./md-rcc8";
import { MdRigidRope } from "./md-rigid-rope";
import { MdRigidStack } from "./md-rigid-stack";
import { MdRouteParams } from "./md-route-params";
import { MdRuntimeTests } from "./md-runtime-tests";
import { MdSelect } from "./md-select";
import { MdSkeletalRig } from "./md-skeletal-rig";
import { MdSketchpad } from "./md-sketchpad";
import { MdSketchpadLive } from "./md-sketchpad-live";
import { MdSliderCrank } from "./md-slider-crank";
import { MdSolarSystem } from "./md-solar-system";
import { MdStringPipeline } from "./md-string-pipeline";
import { MdSyntax } from "./md-syntax";
import { MdTexDemo } from "./md-tex-demo";
import { MdTexLive } from "./md-tex-live";
import { MdTimelineEditor } from "./md-timeline-editor";
import { MdTrails } from "./md-trails";
import { MdTraitsCrossDomain } from "./md-traits-cross-domain";
import { MdTransitions } from "./md-transitions";
import { MdTriTree } from "./md-tri-tree";
import { MdUnitAlgebra } from "./md-unit-algebra";
import { MdUnits } from "./md-units";
import { MdWaapiDemo } from "./md-waapi-demo";

DarkModeToggle.define();
GithubLink.define();
MdSyntax.define();
MdCentering.define();
MdCancel.define();
MdTransitions.define();
MdLayoutDemo.define();
MdTimelineEditor.define();
MdMultitrack.define();
MdCircuit.define();
MdRuntimeTests.define();
MdDebugger.define();
MdChoreography.define();
MdBehaviors.define();
MdBboxHandles.define();
MdBestFit.define();
MdBezierGestalt.define();
MdBireactiveEq.define();
MdBoolBridges.define();
MdSelect.define();
MdLensAlgebra.define();
MdAllen.define();
MdRcc8.define();
MdContainmentForest.define();
MdHistogram.define();
MdHeatmap.define();
MdUnits.define();
MdUnitAlgebra.define();
MdCurveBases.define();
MdFourier.define();
MdBudgetTree.define();
MdSkeletalRig.define();
MdFractalTree.define();
MdTraitsCrossDomain.define();
MdRand.define();
MdTexDemo.define();
MdTexLive.define();
MdWaapiDemo.define();
MdAnchors.define();
MdHandles.define();
MdMultitouch.define();
MdInvertible.define();
MdMerge.define();
MdMirror.define();
MdMix.define();
MdLerps.define();
MdMorph.define();
MdCanvasField.define();
MdCanvasGraph.define();
MdClampQuantize.define();
MdOscillator.define();
MdTrails.define();
MdCode.define();
MdSolarSystem.define();
MdKeplerSystem.define();
MdStringPipeline.define();
MdMadlibs.define();
MdRouteParams.define();
MdFlags.define();
MdTriTree.define();
MdGears.define();
MdPulley.define();
MdIk.define();
MdNetworkLens.define();
MdConfocal.define();
MdConformalDisc.define();
MdSketchpad.define();
MdSketchpadLive.define();
MdBireactive.define();
MdIncidence.define();
MdSliderCrank.define();
MdCloth.define();
MdParticles.define();
MdRigidStack.define();
MdRigidRope.define();
MdFigure8.define();
MdGraph.define();
MdEquation.define();
MdLoop.define();
MdPropFlex.define();
MdPropGeom.define();
MdPropSudoku.define();
MdPropTypes.define();
MdTex.define();
MdMarker.define();
